#!/bin/python3
import os
user=os.getenv('USER') 
os.system("sudo fdisk -l")
drive=input("drive? \n")
os.system("clear")
os.system("ls //media/"+user)
mountPoint=input("Mount Point?")
mountPoint = "/media/"+user + "/" + mountPoint
command = "sudo mount "+ drive + " " + mountPoint + " -o uid="+user",gid=pi"
print(command)
os.system(command)
